version: "3.7"

services:

  signaling-1:
    image: fabri1983dockerid/signaling:dev
    container_name: signaling-1
    ports:
     - 8481:8443
    deploy:
      resources:
        limits:
          memory: 400M

  signaling-2:
    image: fabri1983dockerid/signaling:dev
    container_name: signaling-2
    ports:
     - 8482:8443
    deploy:
      resources:
        limits:
          memory: 400M
